TOPICS = [
    "Artificial intelligence",
    "Machine learning",
    "Deep learning",
    "Data science",
    "Cybersecurity",
    "Cloud computing",
    "Internet of things",
    "Blockchain",
    "Quantum computing",
    "Robotics",
    "Computer vision",
    "Natural language processing",
    "Big data",
    "Data mining",
    "Software engineering",
    "Operating system",
    "Database",
    "Computer network",
    "Information security",
    "Augmented reality",
    "Virtual reality",
    "Space exploration",
    "Climate change",
    "Renewable energy",
    "Electric vehicle",
    "Solar energy",
    "Wind power",
    "Nuclear energy",
    "Mental health",
    "Psychology",
    "Education technology",
    "Online education",
    "Social media",
    "Digital marketing",
    "E-commerce",
    "Finance",
    "Stock market",
    "Cryptocurrency",
    "Economics",
    "Healthcare",
    "Biotechnology",
    "Genetics",
    "Pharmaceutical industry",
    "Environmental science",
    "Sustainability",
    "Urbanization",
    "Transportation",
    "Smart city",
    "Tourism",
    "Agriculture",
    "Food technology",
    "History",
    "Philosophy",
    "Political science",
    "International relations",
    "Law",
    "Ethics",
    "Artificial general intelligence",
    "Human computer interaction",
    "Autonomous vehicle"
]